version: 2.0

workflows:
  flutter_build:
    name: Build Flutter APK
    max_build_duration: 60 # الوقت الأقصى للبناء بالدقائق
    instance_type: mac_mini_m1 # نوع المثيل، اختر النوع المناسب للمشروع
    triggers:
      - push:
          branches:
            - main # أو الفرع الذي تريد تشغيل البناء عليه
    environment:
      vars:
        # متغيرات البيئة، مثل إعدادات التكوين
        FLUTTER_CHANNEL: stable
        FLUTTER_VERSION: 3.7.0
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
