version: 2.0

# تعيين اسم التطبيق الذي سيتم عرضه في لوحة التحكم Codemagic
workflows:
  flutter_build:
    name: Build Flutter APK
    max_build_duration: 60 # الوقت الأقصى للبناء بالدقائق
    instance_type: mac_m1 # نوع المثيل (يمكن أن يكون mac_m1 أو mac_m2)
    triggers:
      - schedule:
          cron: "0 2 * * *" # مثال على جدولة للبناء كل يوم في الساعة 2:00 صباحاً بتوقيت GMT
    environment:
      vars:
        # متغيرات البيئة، مثل إعدادات التكوين
        FLUTTER_CHANNEL: stable
        FLUTTER_VERSION: 3.7.0
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
